source 'https://rubygems.org'

gem 'sinatra', '~> 2'
gem 'sinatra-contrib', '~> 3'

gem 'rack', '~> 2'
gem 'rack-tracer', '~> 0.9'
gem 'jaeger-client', '~> 1.0'

gem 'prometheus-client', '>= 2'

gem 'unicorn',  '>= 5',  '< 6'

gem 'fog-proxmox', '0.15.0'

gem 'sinatra-instrumentation'
